### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by mpolonioli** [ldbc/ldbc_snb_driver#79] opened 2017-10-07 22:36 UTC
I write the implementation of the driver for JanusGraph DB, but when I run the benchmark I'm getting the following error at the end of the warmup phase: 
```
Shutting down status thread...
00:29:20,403  INFO ExecuteWorkloadMode:37 - Shutting down workload...
00:29:20,404  INFO ExecuteWorkloadMode:37 - Shutting down completion time service...
00:29:20,505  INFO ExecuteWorkloadMode:37 - Shutting down metrics collection service...
Exception in thread "main" java.lang.NoSuchMethodError: com.lmax.disruptor.dsl.Disruptor.shutdown(JLjava/util/concurrent/TimeUnit;)V
	at com.ldbc.driver.runtime.metrics.DisruptorSbeMetricsService.shutdown(DisruptorSbeMetricsService.java:161)
	at com.ldbc.driver.client.ExecuteWorkloadMode.doExecute(ExecuteWorkloadMode.java:424)
	at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:111)
	at com.ldbc.driver.Client.main(Client.java:53)
```

**Comment by szarnyasg** [comment] 2021-12-12 12:34
I have never come across this issue and cannot reproduce it, so closing this or now. Feel free to reopen if it occurs again.

**Closed by szarnyasg** 2021-12-12 12:34 UTC
